Repository CA-G12/Quran-Application, pull requests merged in 2022-08, with the labels that each got.

#2 Created file sturcutre
  test/test.js
Labels: waiting review

#4 created file structure
  css/style.css
  index.html
  js/dom.js
  js/fetch.js
  js/logic.js
Labels: waiting review

#6 adding readme file
  README.md
Labels: waiting review

#7 Created fetch functionality in fetch.js
  js/fetch.js
Labels: waiting review

#9 add home page html
  css/style.css
  index.html
Labels: waiting review

#11 Updates on rendering dropdown lists data
  js/dom.js
Labels: waiting review

#13 get surah values from api and show them in the drop down menu
  js/dom.js
Labels: done

#15 Get ayahs items
  js/dom.js
Labels: waiting review

#16 show surah content but needs changes
  css/style.css
  index.html
  js/dom.js
  js/surah.js
Labels: waiting review

#18 Get recieters
  index.html
  js/dom.js
  js/logic.js
  js/surah.js
Labels: waiting review

#19 fix show suruh in the main page
  js/surah.js
Labels: waiting review

#21 refactored surah.js and make the code in one function (renderAyas) t…
  js/dom.js
  js/surah.js
Labels: waiting review

#25 Sound palyer
  css/style.css
  index.html
  js/dom.js
  js/player.js
Labels: approved

#28 make the website responsive
  css/style.css
  index.html
  js/surah.js
Labels: waiting review

#29 27 refactoring code
  .gitignore
  css/style.css
  images/giphy.webp
  images/loading.webp
  index.html
  js/dom.js
  js/logic.js
  js/surah.js
  package-lock.json
  package.json
Labels: waiting review

#31 finished testing
  js/logic.js
  test/test.js
Labels: waiting review

#32 fixed error in surah name in media player
  js/dom.js
Labels: waiting review

#36 fixed move up style
  css/style.css
  js/dom.js
Labels: waiting review

#37 changes on move-up button style
  css/style.css
Labels: waiting review
